---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: "us-west-2"
    env: "sandbox"
    instance_type: "m3.medium"
    size: "80"
    cluster_size: "3"
  vars_prompt:
    project: "Project name"
    key: "Name of the ssh key to use"
    owner: "E-Mail address of the technical owner"
    ami: "AMI Id"
    client_security_group: "Security Group ID of storage clients"
  tasks:
  - name: Discover SSSG Id
    action: uri url=http://ui.{{ region }}.consul.{{ env }}.nubis.allizom.org/v1/kv/environments/{{ env }}/global/aws/sssg_security_group?raw return_content=yes
    register: sssg_security_group
  - name: Discover Internet SG Id
    action: uri url=http://ui.{{ region }}.consul.{{ env }}.nubis.allizom.org/v1/kv/environments/{{ env }}/global/aws/internet_access_security_group?raw return_content=yes
    register: internet_access_security_group
  - name: Nubis Storage
    cloudformation:
      stack_name: "{{project}}-storage"
      region: "{{ region }}"
      state: "present"
      disable_rollback: true
      template: "main.json"
      template_parameters:
        ProjectName: "{{ project }}"
        KeyName: "{{ key }}"
        InstanceType: "{{ instance_type }}"
        TechnicalOwner: "{{ owner }}"
        VolumeSize: "{{ size }}"
        ClusterSize: "{{ cluster_size }}"
        AMI: "{{ ami }}"
        InternetAccessSecurityGroup: "{{ internet_access_security_group.content }}"
        SSSG: "{{ sssg_security_group.content }}"
        ClientSecurityGroup: "{{ client_security_group }}"
    register: stack 
  - debug: var=stack.stack_outputs
