---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: "us-west-2"
    env: "sandbox"
    instance_type: "m3.medium"
    size: "80"
    cluster_size: "3"
  vars_prompt:
    project: "Project name"
    key: "Name of the ssh key to use"
    owner: "E-Mail address of the technical owner"
    client_security_group: "Security Group ID of storage clients"
  tasks:
  - name: Nubis Storage
    cloudformation:
      stack_name: "{{project}}-storage"
      region: "{{ region }}"
      state: "present"
      disable_rollback: true
      template: "main.json"
      template_parameters:
        ServiceName: "{{ project }}"
        StackName: "{{project}}-storage"
        SSHKeyName: "{{ key }}"
        InstanceType: "{{ instance_type }}"
        TechnicalOwner: "{{ owner }}"
        VolumeSize: "{{ size }}"
        ClusterSize: "{{ cluster_size }}"
        EC2SecurityGroup: "{{ client_security_group }}"
    register: stack 
  - debug: var=stack.stack_outputs
